CHANGELOG.md, src/gleam_otp_external.erl, test/gleam/otp/process_test.gleam
I went for a very minimal fix as a first pass, just making sure port messages can received with `bare_message_receiver()`
=> Don't treat port messages as a closed channel

.github/workflows/test.yml, src/gleam/otp/actor.gleam, src/gleam/otp/process.gleam, src/gleam/otp/supervisor.gleam, test/gleam/otp/process_test.gleam
Removing compiler warnings from gleam/otp when compiled with gleam 0.14.
Some comments:
* The changes in `supervisor.gleam` is due to a bug (gleam-lang/gleam#989)
* The problem with unused warning for import `gleam/opt/port.{Port}` might mask another problem. `Port` is used as a constructor in another type in the module but it is actually `port.Port` that should be used (I think). I'd expect the compiler to fail here because of ambiguous use of types. I worked around the warning by using the type explicitly
* I am unsure of the changes `process_test.gleam` relating to `ExitStatus`. As a quick workaround I add the `ExitStatus` to the `open_port` function. It passes the unit tests but I don't know if there are any side effects. The `ExitStatus` flags makes the port send an exit status …
=> Remove compiler warnings when compiled with 0.14

CHANGELOG.md, gleam.toml, manifest.toml, src/gleam/otp/process.gleam, src/gleam_otp_external.erl, test/gleam/otp/process_test.gleam
As discussed a couple of days ago on Discord, I thought I would have a go at adding a `pid_from_dynamic` function to the `process` module. I think this is a handy function for certain use cases, for example if you have an Erlang or Elixir process that sends its own pid in a message to a Gleam actor, and you want to reply to it using `process.untyped_send`.
You mentioned that you would prefer to write the decoder in Erlang, so I had a go at that - it's the first Erlang I've ever written, so apologies if there are any blunders. I wrote a couple of tests and they seem to pass, so hopefully it's ok.
This my second pull request on any project ever, so apologies if I have done anything stupid :)
=> Add pid_from_dynamic to process module

CHANGELOG.md, src/gleam/otp/task.gleam, test/gleam/otp/task_test.gleam
Noticed these were missing but that there is a `process.receive_forever` so I figured It might be worth including these
=> task.await_forever and task.try_await_forever

CHANGELOG.md, src/gleam/otp/task.gleam, test/gleam/otp/task_test.gleam, test/gleam_otp_test_external.erl
Resolves: #39
I've unit tested this by checking the actor's mailbox using erlang's `process_info`.
There might be a more elegant way of doing this.
=> Unmonitor task when done

src/gleam/otp/actor.gleam
Currently, neither `from_erlang_start_result` nor `wrap_erlang_starter` exist.
=> Remove outdated comment

CHANGELOG.md, src/gleam/otp/actor.gleam, src/gleam/otp/system.gleam, src/gleam_otp_external.erl
Between Erlang/OTP 26.0 and 26.1, the interface for system messages changed from a literal type to result type, breaking our implementation. See [OTP-18633](https://www.erlang.org/patches/otp-26.1#stdlib-5.1) for more information.
This patch updates the library to 26.1, but sets a minimum version requirement. Since this is such a niche API (debugging only), we agreed that documentation is sufficient to enforce versions.
*Open Questions*
Tests pass locally, though some files need a reformat. Will address separately.
```
kdmb@nas ~/g/k/gleam_otp (fix/erlang_system_message_interface)> asdf current erlang
erlang          26.1.2          /home/kdmb/.tool-versions
kdmb@nas ~/g/k/gleam_otp (fix/erlang_system_message_interface)> gleam test
Compiling gleam_otp
Compiled in 0.34s
Running …
```
=> fix: system message returned from GetState

CHANGELOG.md, src/gleam/otp/intensity_tracker.gleam, test/gleam/otp/intensity_tracker_test.gleam
Summary: The IntensityTracker does not short-circuit due to a logic bug in recursion.
Expected behavior: If I set a limit of 5 restarts per minute, I expect six restarts to throw the error `TooIntense`
Actual behavior: The error does not throw, no matter how many times the supervisor restarts a child.
Explanation:
On the first event sent to the intensity_tracker:
`now == event`
So the subsequent logical check into recursion:
`now >= event + period`
always evaluated `False` given the default restart period. The event was always stripped from internal state, so the intensity_tracker never held more than one event at a time. The code in question:
https://github.com/gleam-lang/otp/blob/45deedf1fe9fead77d84b19cdf613cc6b41a3ae1/src/gleam/otp/intensity_tracker.gleam#L26-L35
This patch also …
=> Fix: IntensityTracker properly returns error when limit is exceeded

src/gleam/otp/actor.gleam
Small stuff I noticed while reading the actor docs.
=> docs: fix typos and wording for Actors

src/gleam/otp/actor.gleam
Should this function argument be called `subject`, since it's of type `Subject`?
=> Variable name type mismatch

src/gleam/otp/actor.gleam
I asked around [in discord](https://discord.com/channels/768594524158427167/1243107995382972416/1243107995382972416) how
```gleam
let assert Ok(actor) = actor.start([], handle_message)
```
is valid syntax. Apparently `actor` can be shadow the imported module.
What do we think about renaming the variable name in the example to not try to confuse things?
=> Differentiate instansiated actor vs actor module

src/gleam/otp/actor.gleam
It looks like this link is producing a 404 and is going to https://hexdocs.pm/gleam_otp/gleam/otp/erlang-sys
=> Fix `erlang-sys` link

src/gleam/otp/actor.gleam
Nothing significant. After undoing some changes (related to below paragraph) it's only one typo fix and one legibility improvement.
I noticed that the docs use the word "initialise" instead of "initialize." Based on rudimentary research, it seems that "initialize" is the more American English spelling while "initialise" is the more British English spelling, except that even in Britain "initialize" seems to be the more common spelling. If this is something that wants to be changed, I wouldn't mind adding more commits changing the occurrences of "initialise" to "initialize".
=> Typo corrections and legibility improvements in actor docs

src/gleam/otp/actor.gleam, test/gleam/otp/actor_test.gleam
Resolves #73
In addition to returning an error, a timed out actor init would also propagate the exit message to the parent process, causing it to get killed unless it was trapping exits.
=> Fix actor init timeout sending exit message to linked parent

gleam.toml, src/gleam_otp_external.erl
=> fix: return error when supervisor:start_link/2 fails

CHANGELOG.md, src/gleam/otp/actor.gleam, test/gleam/otp/actor_test.gleam
Resolves #89
The actor would stop with `Normal` before this.
=> Make `actor.Stop` respect the given exit reason

src/gleam_otp_external.erl
This will give the observer status printout:
as compared to the current:
=> Make observer status printout pretty

README.md
=> Fix word duplication typo in README

CHANGELOG.md, src/gleam/otp/actor.gleam
This PR hopes to resolve #108 and improve the documentation for `actor.start`
Additionally, I added the missing `actor.set_timeout` to the library, as brought to light by @lpil in the same issue.
=> Added `actor.set_timeout` function and improved documentation for `actor.start`

CHANGELOG.md, README.md, gleam.toml, manifest.toml, src/gleam/otp/factory_supervisor.gleam, src/gleam/otp/internal/result2.gleam, src/gleam/otp/static_supervisor.gleam, src/gleam/otp/supervision.gleam, src/gleam_otp_external.erl, test/gleam/otp/factory_supervisor_test.gleam
A module for supervision of processes of a fixed type which are dynamically started while the program is running! aka Erlang's "simple one for one" supervisor.
=> Factory supervisor for supervision of dynamic processes
